title: DEF CON Hardware Hacking Village
theme: jekyll-theme-hacker
description: We make our own use for things
baseurl: ""
url: ""
twitter_username: dc_hhv
github_username:  dchhv
email: l33tbunni@dchhv.org
